version: "3.9"  # optional since v1.27.0

networks:
  network_shrurl:

services:

  web_app:
    build:
      context: .
      dockerfile: ShrURL/Dockerfile
    # container_name: shrurl_webapp
    ports:
      - "5129:8080" # HTTP
      - "7111:8081" # HTTPS
    networks:
      - network_shrurl
    depends_on:
      - sql_server

  sql_server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    # container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
      #- DB_CONNECTION_STRING=Server=sql_server;Database=ShrURL;User Id=SA;Password=A&VeryComplex123Password;MultipleActiveResultSets=true;TrustServerCertificate=True;Encrypt=false;
    networks:
      - network_shrurl